### ISSUE TITLE
Draft is ready to be reviewed

### ISSUE THREAD

**Issue by luxorina** [Bucknell-Biol364/Biology207tutorial#1]
https://github.com/Bucknell-Biol364/Biology207tutorial/blob/90c8404f6b30e7d8f8a8e6a69a8056d5cd1ce9b0/Biology%20207%20tutorial.Rmd#L1

@KField-Bucknell @mwm021

**Comment by KField-Bucknell** [comment]
You have made some good progress and I think that it will make a nice screencast. I opened an issue about loading in the data, but I have now looked at the script and you plan on loading it within R Studio. I think that it might be a good idea to have the code in your Rmd anyway.

I would also suggest that you consider how to use the README file to help the students get started.

**Comment by KField-Bucknell** [comment]
Great work on the video. In addition to the minor change about jitter, I hope that you can also add a regression line to the plot. Maybe after you go over the lm fit, you can then add another code chunk to plot the line on the graph (along with 95% confidence intervals)?
